import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowUpRight, CaretLeft, CaretRight, CaretUp, DownloadSimple, Phone, Headset, ShieldCheck, Truck, Tree, Wine, Diamond, Stack, Wind, Lightning, Target, Camera, Thermometer, Monitor, WifiHigh, Play, Pause, X, MagnifyingGlassPlus, CubeFocus, CheckCircle } from '@phosphor-icons/react';
import { HomeNavigation, HomeFooter } from './Home.jsx';
import prices from './data/hydra-prices.json';
import { initializeAnalytics, trackEvent } from './analytics.js';
import './components/CommercialCapabilities.css';
import { hydraFilm, HydraFilm, HydraSpotlight, HydraVideoRail, HydraComparison, HydraDecisionPaths, HydraVideoModal } from './components/HydraVideos.jsx';

const asset = n => `${import.meta.env.BASE_URL}assets/${n}`;
const brochure = `${import.meta.env.BASE_URL}downloads/onelaser-hydra-gen2-brochure.pdf`;
const call = 'https://www.1laser.com/products/sales-consultation-call';
const money = n => new Intl.NumberFormat('en-US', { style:'currency', currency:'USD', maximumFractionDigits:0 }).format(n);
const models = {
  7: { area:'700 × 500 mm', inches:'27.6 × 19.7 in', fit:'Focused production', dc:null, dimensions:'1,300 × 1,045 × 1,035 mm', load:'20 kg' },
  9: { area:'900 × 600 mm', inches:'35.4 × 23.6 in', fit:'Room to grow', dc:100, dimensions:'1,500 × 1,045 × 1,035 mm (Pro); 1,900 × 1,045 × 1,035 mm (Hybrid)', load:'30 kg' },
  13:{ area:'1,300 × 900 mm', inches:'51.2 × 35.4 in', fit:'Larger batches', dc:130, dimensions:'1,900 × 1,445 × 1,035 mm', load:'30 kg' },
  16:{ area:'1,600 × 1,000 mm', inches:'63.0 × 39.4 in', fit:'Large-format ambition', dc:150, dimensions:'2,200 × 1,545 × 1,035 mm', load:'30 kg' },
};
const materials = [
  { name:'Wood', icon:Tree, image:'hydra-ai-detail.webp', title:'Turn natural grain into extraordinary detail.', copy:'Photo engraving, layered artwork and personalized wood products. RF control brings out fine textures and smooth grayscale.', mode:'RF engraving · CO₂ cutting' },
  { name:'Acrylic', icon:Diamond, image:'hydra-ai-acrylic.webp', title:'Make your next statement in acrylic.', copy:'From engraved clear acrylic to precisely cut shapes, create signage, display pieces and decorative products.', mode:'RF engraving · CO₂ cutting' },
  { name:'Leather', icon:Stack, image:'hydra-ai-leather.webp', title:'A personal touch people can feel.', copy:'Add detailed artwork to laser-compatible leather journals, patches and accessories. Test material composition before processing.', mode:'RF engraving · CO₂ cutting' },
  { name:'Drinkware', icon:Wine, image:'hydra-ai-projects.webp', title:'Take your designs all the way around.', copy:'Personalize glass and powder-coated drinkware. Cylindrical work requires a compatible optional 4-pin rotary.', mode:'RF engraving · Optional rotary required' },
];
const chapters = [
  { id:'speed', label:'Speed & motion', title:'Real speed.\nReady for production.', copy:'Move from one job to the next with up to 2,000 mm/s raster engraving and 4G acceleration. A high-speed servo system and rigid, vibration-optimized mechanics keep detail at the center of the work.', image:'hydra-motion.webp', alt:'Hydra Gen2 precision motion system', metrics:[['2,000','mm/s raster speed'],['4G','acceleration']], proofs:[[Lightning,'High-speed servo','Responsive motion for demanding production.'],[Target,'≤ 0.01 mm','Repeat positioning accuracy.']] },
  { id:'air', label:'Smart dual air', title:'The right airflow.\nAutomatically.', copy:'Gentle air for clean, detailed engraving. Stronger air for efficient cutting. Smart Dual Air-Assist switches with the job, through your software, so there is less manual adjustment between processes.', image:'hydra-official-05.webp', alt:'Hydra low-air engraving and high-air cutting modes', proofs:[[Wind,'Low air','Keeps engraved detail clear.'],[Wind,'High air','Supports cutting and cleaner edges.']] },
  { id:'workflow', label:'Visual workflow', title:'Less setup.\nMore making.', copy:'Position the artwork with the camera, set the focal distance automatically and check placement with the red dot. Move confidently from a one-off design to the next repeat job.', image:'hydra-workflow.webp', alt:'Hydra Gen2 open working bed and camera-ready positioning', proofs:[[Camera,'Visual positioning','Millimeter-level placement assistance.'],[CubeFocus,'Autofocus + red dot','Automatic Z-axis focusing and visible alignment.']] },
  { id:'reliability', label:'Reliability & safety', title:'Built for the\nlong run.', copy:'Real-time lens temperature monitoring warns of overheating or contamination. A rigid, NVH-optimized structure supports consistent output, while the enclosed chassis separates electronics from the working area.', image:'hydra-official-07.webp', alt:'Hydra Gen2 lens temperature monitoring', proofs:[[Thermometer,'Detect. Alert. Protect.','Temperature alarms and laser-output shutoff.'],[ShieldCheck,'Integrated interlocks','Lid and side-panel safety interlocks.']] },
  { id:'format', label:'Room to create', title:'Go longer.\nThink bigger.', copy:'Four work areas give your business room to scale. Front-to-back pass-through doors accommodate longer stock; a 225 mm Z-axis travel supports varied workpiece heights.', image:'hydra-official-11.webp', alt:'Hydra Gen2 front-to-back material pass-through', proofs:[[Stack,'225 mm','Maximum Z-axis bed travel.'],[ArrowUpRight,'Front-to-back','20 mm pass-through opening.']] },
];
const opportunitySets = [
  {label:'Personalized Gifts',copy:'Thoughtful products with a personal touch.',items:[['Wood portraits','hydra-ai-detail.webp','Wood','Detailed RF engraving','Use tested grayscale settings on flat, laser-compatible wood.'],['Leather keepsakes','hydra-ai-leather.webp','Leather','RF engraving','Confirm the leather composition and test settings before production.'],['Acrylic gifts','hydra-ai-acrylic.webp','Acrylic','Engraving & cutting','Choose compatible acrylic and appropriate settings for the source.']]},
  {label:'Home & Décor',copy:'Detailed decorative work, from the studio to the living space.',items:[['Engraved wall art','hydra-ai-detail.webp','Wood','RF grayscale','Size the artwork to the bed and test detail on the chosen stock.'],['Botanical displays','hydra-ai-acrylic.webp','Acrylic','Engraving & cutting','Use a jig for repeatable placement and inspect finished edges.'],['Coordinated gift sets','hydra-ai-projects.webp','Mixed materials','Multiple processes','Prepare separate settings for each material. Rotary required for cylindrical items.']]},
  {label:'Drinkware & Events',copy:'Personalized pieces for events and branded gifting.',items:[['Coated drinkware','hydra-ai-projects.webp','Powder-coated metal','RF coating removal','Requires a compatible optional rotary and suitable coating.'],['Table displays','hydra-ai-acrylic.webp','Acrylic','Engraving & cutting','Lay out repeat shapes and confirm acrylic compatibility.'],['Event keepsakes','hydra-ai-leather.webp','Leather','RF engraving','Use approved laser-compatible leather and repeatable fixtures.']]},
  {label:'Branded Goods',copy:'Turn repeatable details into a consistent product collection.',items:[['Leather patches','hydra-ai-leather.webp','Leather','Batch engraving','Prepare a batch fixture and validate one sample before running the set.'],['Display pieces','hydra-ai-acrylic.webp','Acrylic','Engraving & cutting','Match laser configuration to the detail and cutting workload.'],['Wooden merchandise','hydra-ai-detail.webp','Wood','RF engraving','Tune grayscale, speed and power to the chosen wood.']]},
];
const chapterNav = [{id:'laser-guide',label:'RF precision'}, ...chapters];
const navItems = [['possibilities','Overview'],['performance','Features'],['product-opportunities','Projects'],['materials','Materials'],['specifications','Specifications'],['reviews','Reviews']];

function Img({ name, alt='', className='', eager=false, ...props }) {
  const [state,setState]=useState('loading');
  return <img {...props} className={`h-image ${state==='ready'?'is-image-ready':''} ${className}`} src={asset(name)} alt={alt} loading={eager?'eager':'lazy'} decoding="async" onLoad={()=>setState('ready')} onError={()=>setState('error')} data-image-state={state}/>;
}
function Heading({ eyebrow, title, children, center=false }) {
  return <div className="section-heading section-heading--stack"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{children && <p>{children}</p>}</div>;
}
function Link({href=call, children, secondary=false, ...props}) {
  return <a className={secondary?'h-link':'primary-cta'} href={href} target="_blank" rel="noreferrer" onClick={()=>trackEvent('generate_lead',{destination:href})} {...props}>{children}<ArrowUpRight size={18}/></a>;
}
function SpecGroup({ title, rows }) {
  const [open,setOpen]=useState(false);
  return <div className={`spec-group ${open?'is-open':''}`}><button className="spec-group__trigger" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><span>{title}</span><span aria-hidden="true">{open?'−':'+'}</span></button>{open&&<div className="spec-group__rows">{rows.map(([label,value])=><div className="spec-row" key={label}><span>{label}</span><div><strong>{value}</strong></div></div>)}</div>}</div>;
}
function Preview({ item, close }) {
  const dialog=useRef(null);
  useEffect(()=>{
    const prior=document.activeElement; const overflow=document.body.style.overflow;
    document.body.style.overflow='hidden'; dialog.current?.focus();
    function keys(e){if(e.key==='Escape')close();if(e.key==='Tab'){e.preventDefault();dialog.current?.querySelector('button')?.focus();}}
    window.addEventListener('keydown',keys);
    return()=>{window.removeEventListener('keydown',keys);document.body.style.overflow=overflow;prior?.focus();};
  },[close]);
  return <div className="h-modal" onClick={close}><div ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-label={item.alt} onClick={e=>e.stopPropagation()}><button className="h-round h-modal-close" onClick={close} aria-label="Close image preview"><X size={24}/></button><Img name={item.name} alt={item.alt} eager/><p>{item.alt}</p></div></div>;
}

export function HydraPage() {
  const [model,setModel]=useState('9'); const [config,setConfig]=useState('Hybrid');
  const [video,setVideo]=useState(null); const closeVideo=useCallback(()=>setVideo(null),[]);
  const [gallery,setGallery]=useState(0); const [preview,setPreview]=useState(null); const closePreview=useCallback(()=>setPreview(null),[]);
  const [material,setMaterial]=useState(0); const [paused,setPaused]=useState(false); const [interacting,setInteracting]=useState(false); const [epoch,setEpoch]=useState(0);
  const [rfTab,setRfTab]=useState(0); const [powerTab,setPowerTab]=useState(0); const [openFaq,setOpenFaq]=useState(0); const [opportunity,setOpportunity]=useState(0); const [product,setProduct]=useState(0);
  const [specModel,setSpecModel]=useState('9'); const [activeNav,setActiveNav]=useState('possibilities'); const [activeChapter,setActiveChapter]=useState('laser-guide');
  const [sticky,setSticky]=useState(false);const [topVisible,setTopVisible]=useState(false);
  const [reduced,setReduced]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  const thumbs=useRef(null);const touchX=useRef(null); const matTouch=useRef(null);
  const m=models[model]; const p=prices[model]; const variant=p.variants.find(v=>v.title.includes(config)) || p.variants[0];
  const purchaseUrl=`${p.url}?variant=${variant.id}&utm_source=hydra-gen2-listing&utm_medium=product-page`;
  const galleryItems=[{name:`hydra-${model}-hero.webp`,alt:`OneLaser Hydra ${model} Gen2 machine`}, ...(model==='9'?[{name:'hydra-front.webp',alt:'Hydra 9 Gen2 front view'},{name:'hydra-workflow.webp',alt:'Hydra 9 Gen2 open bed view'}]:[]), {name:'hydra-ai-projects.webp',alt:'Application concept: laser-engraved and cut products'},{name:'hydra-official-05.webp',alt:'Smart Dual Air-Assist'},{name:'hydra-official-07.webp',alt:'Lens temperature protection'},{name:'hydra-official-14.webp',alt:'GT5 touchscreen and keypad'}];
  const currentImage=galleryItems[gallery%galleryItems.length];
  const mat=materials[material]; const selectedProduct=opportunitySets[opportunity].items[product];
  function chooseModel(n){setModel(n);if(n==='7')setConfig('Pro');setGallery(0);trackEvent('select_model',{model:n});}
  function selectMaterial(n){setMaterial((n+materials.length)%materials.length);setEpoch(e=>e+1);}
  function step(n){setGallery(i=>(i+n+galleryItems.length)%galleryItems.length);}
  function navigate(id){document.getElementById(id)?.scrollIntoView({behavior:reduced?'auto':'smooth'});trackEvent('navigate_section',{section_id:id});}
  useEffect(()=>{
    initializeAnalytics();trackEvent('view_content',{content_name:'Hydra Gen2',content_type:'product'});
    const mq=window.matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setReduced(mq.matches);mq.addEventListener('change',change);return()=>mq.removeEventListener('change',change);
  },[]);
  useEffect(()=>{
    let prev=window.scrollY; const onScroll=()=>{const y=window.scrollY;setSticky((document.getElementById('top')?.getBoundingClientRect().bottom ?? 9999)<132);setTopVisible(y>700&&y<prev);prev=y;};
    window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll);
  },[]);
  useEffect(()=>{
    const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){if(navItems.some(([id])=>id===e.target.id))setActiveNav(e.target.id);if(chapterNav.some(c=>c.id===e.target.id))setActiveChapter(e.target.id);}});},{rootMargin:'-20% 0px -55% 0px',threshold:0});
    [...navItems.map(([id])=>id),...chapterNav.map(c=>c.id)].forEach(id=>{const el=document.getElementById(id);if(el)observer.observe(el);});return()=>observer.disconnect();
  },[]);
  useEffect(()=>{if(paused||interacting||reduced)return;const t=setTimeout(()=>setMaterial(n=>(n+1)%materials.length),6000);return()=>clearTimeout(t);},[material,paused,interacting,reduced,epoch]);

  return <div className="site-shell home-global-chrome hydra-page">
    <a className="skip-link" href="#main">Skip to content</a><HomeNavigation megaMenuActivation="click"/>
    <main id="main">
      <section className="hero section h-hero" id="top">
        <div className="hero-media">
          <div className="media-stage" role="region" aria-label="Hydra product gallery" aria-roledescription="carousel" tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();step(1);}if(e.key==='ArrowLeft'){e.preventDefault();step(-1);}}} onTouchStart={e=>touchX.current=e.changedTouches[0].clientX} onTouchEnd={e=>{if(touchX.current!==null&&Math.abs(e.changedTouches[0].clientX-touchX.current)>44)step(e.changedTouches[0].clientX<touchX.current?1:-1);touchX.current=null;}}>
            <button className="h-gallery-open" onClick={()=>setPreview(currentImage)} aria-label="Enlarge product image"><Img key={currentImage.name} name={currentImage.name} alt={currentImage.alt} eager/><span className="h-enlarge"><MagnifyingGlassPlus size={20}/></span></button>
            <span className="media-count">{String(gallery%galleryItems.length+1).padStart(2,'0')} / {String(galleryItems.length).padStart(2,'0')}</span>
            <button className="media-arrow media-arrow--previous" aria-label="Previous product view" onClick={()=>step(-1)}><CaretLeft size={24}/></button><button className="media-arrow media-arrow--next" aria-label="Next product view" onClick={()=>step(1)}><CaretRight size={24}/></button>
          </div>
          <div className="thumbnail-controls"><button className="thumb-arrow" aria-label="Scroll product thumbnails left" onClick={()=>thumbs.current?.scrollBy({left:-240,behavior:reduced?'auto':'smooth'})}><CaretLeft size={20}/></button><div className="thumbnail-row" ref={thumbs}>{galleryItems.map((im,i)=><button className={`thumbnail ${i===gallery?'is-active':''}`} key={im.name} aria-label={`Show product view ${i+1}`} aria-pressed={i===gallery} onClick={()=>setGallery(i)}><Img name={im.name}/></button>)}</div><button className="thumb-arrow" aria-label="Scroll product thumbnails right" onClick={()=>thumbs.current?.scrollBy({left:240,behavior:reduced?'auto':'smooth'})}><CaretRight size={20}/></button></div>
          <button className="h-hero-video" onClick={()=>setVideo(hydraFilm)} aria-label="Watch the official Hydra Gen2 film"><span><img src={asset(hydraFilm.cover)} alt="" width="1280" height="720"/><Play size={20} weight="fill"/></span><strong>Hydra Gen2 in action<small>Official film · Stitchcraft Interiors</small></strong><ArrowUpRight size={18}/></button>
          <div className="hero-assurance-grid"><a className="hero-assurance-card hero-assurance-card--link" href={call} target="_blank" rel="noreferrer"><Phone size={28}/><strong>Book A Free Call</strong><ArrowUpRight className="hero-assurance-card__arrow" size={15}/></a><a className="hero-assurance-card hero-assurance-card--link" href={brochure} target="_blank" rel="noreferrer"><DownloadSimple size={28}/><strong>Download Brochure</strong><ArrowUpRight className="hero-assurance-card__arrow" size={15}/></a><a className="hero-assurance-card hero-assurance-card--link" href="https://www.1laser.com/pages/contact-us" target="_blank" rel="noreferrer"><Headset size={28}/><strong>U.S.-based Engineers with Lifetime Support</strong><ArrowUpRight className="hero-assurance-card__arrow" size={15}/></a><div className="hero-assurance-card"><ShieldCheck size={28}/><strong>Up to 3-Year Warranty</strong></div></div>
        </div>
        <div className="purchase-panel">
          <h1>OneLaser Hydra™ {model} Gen2<br/>Industrial RF Laser Engraver</h1>
          <p className="h-hero-description">Sharper detail. Faster output.<br/>Built around the way you produce.</p>
          <ul className="hero-highlights"><li><strong>Production speed:</strong> up to 2,000 mm/s · 4G acceleration.</li><li><strong>RF precision:</strong> up to 2,000 DPI · 0.07 mm spot.</li><li><strong>Work area:</strong> {m.area} ({m.inches}).</li><li><strong>Smarter workflow:</strong> autofocus · dual air-assist · GT5 control.</li></ul>
          <div className="official-price"><div className="official-price__main"><span>Hydra {model} {config}</span><strong>{money(variant.price)} <small>USD</small></strong></div></div><p className="h-footnote">Shipping and taxes calculated on the official store.</p>
          <a className="h-financing" href="https://www.1laser.com/pages/financing" target="_blank" rel="noreferrer">Explore financing options <ArrowUpRight size={14}/></a>
          <fieldset className="h-options"><legend>Choose your workspace</legend><div className="h-model-options">{Object.keys(models).map(n=><button key={n} className={n===model?'is-selected':''} aria-pressed={n===model} onClick={()=>chooseModel(n)}><strong>Hydra {n}</strong><span>{models[n].area}</span></button>)}</div></fieldset>
          <fieldset className="h-options"><legend>Choose your laser configuration</legend><div className="purchase-power-options">{['Hybrid','Pro'].map(c=><button key={c} disabled={model==='7'&&c==='Hybrid'} className={`purchase-power ${c===config?'is-selected':''}`} aria-pressed={c===config} onClick={()=>{setConfig(c);trackEvent('select_configuration',{model,configuration:c});}}><strong>{c==='Pro'?'70W RF Pro':`38W RF + ${m.dc||'DC'}${m.dc?'W DC':''}`}</strong><span>{c==='Pro'?'Fine detail & dedicated RF production':model==='7'?'Available on Hydra 9, 13 & 16':'RF engraving & powerful glass-tube cutting'}</span></button>)}</div></fieldset>
          <div className="h-config-note"><ShieldCheck size={20}/><p>{config==='Pro'?'Air-cooled RF source. Optional fiber expansion on supported 70W configurations.':'Air-cooled RF engraving + water-cooled DC cutting. Confirm the matching chiller with your engineer.'}</p></div>
          <a className="primary-cta h-purchase" href={purchaseUrl} target="_blank" rel="noreferrer" onClick={()=>trackEvent('purchase_intent',{model,configuration:config,value:variant.price,currency:'USD'})}>Configure on official store<ArrowUpRight size={20}/></a>
          <p className="h-purchase-note">U.S.-based lifetime support · 1-on-1 setup guidance</p>
          <details className="h-addons"><summary>Optional accessories & upgrades <span>+</span></summary><p>Compatible 4-pin rotary, LightBurn Pro license, additional lenses and fume filtration. Fiber upgrades are optional, subject to release and compatibility confirmation. Request a quote for the complete setup.</p><Link secondary>Plan your setup</Link></details>
        </div>
      </section>

      <nav className={sticky?'journey-nav is-visible':'journey-nav'} aria-label="Explore Hydra Gen2"><div className="journey-nav__inner"><div className="journey-nav__rail">{navItems.map(([id,label],i)=><button key={id} onClick={()=>navigate(id)} className={activeNav===id?'is-active':''} aria-current={activeNav===id?'location':undefined}><span>{label}</span><small>{String(i+1).padStart(2,'0')}</small></button>)}</div><span className="journey-nav__count">{String(navItems.findIndex(([id])=>id===activeNav)+1).padStart(2,'0')}<i>/</i>06</span></div></nav>

      <section className="h-section" id="possibilities"><div className="h-wrap"><Heading eyebrow="HYDRA GEN2" title={<>The end game of<br/>performance laser.</>}>RF engraving quality, real production speed and scalable working sizes. Built to complete more jobs, create higher-value products and grow with your business.</Heading><figure className="h-wide-image"><Img name="hydra-ai-projects.webp" alt="Conceptual laser applications in wood, leather, acrylic, slate and powder-coated drinkware"/><figcaption>Application inspiration · AI-generated concept. Results depend on material and settings.</figcaption></figure><div className="h-metrics">{[['2,000 mm/s','Raster engraving speed'],['4G','Production acceleration'],['2,000 DPI','Maximum scanning precision'],['4 workspaces','From 700 × 500 to 1,600 × 1,000 mm']].map(([v,l])=><div key={v}><strong>{v}</strong><span>{l}</span></div>)}</div></div></section>

      <HydraFilm onPlay={setVideo}/>
      <HydraSpotlight onPlay={setVideo}/>
      <HydraVideoRail onPlay={setVideo}/>

      <section className="capability-scroll hydra-capability" id="performance"><nav className="capability-scroll__nav" style={{'--active-chapter':chapterNav.findIndex(c=>c.id===activeChapter)}} aria-label="Hydra engineering chapters">{chapterNav.map(c=><button key={c.id} onClick={()=>navigate(c.id)} className={activeChapter===c.id?'is-active':''} aria-current={activeChapter===c.id?'location':undefined}><strong>{c.label}</strong></button>)}</nav>
      <section className="rf-advantages" id="laser-guide"><div className="rf-advantages__inner"><header className="rf-advantages__header"><span className="eyebrow">WHY RF TUBE</span><h2>Why makers choose RF tube.</h2><p>Fine textures, smooth grayscale and responsive power control. Built for premium personalization and daily production.</p></header><div className="rf-advantages__tabs" role="group" aria-label="RF advantages">{['Fine detail','Longer life','Power control'].map((t,i)=><button key={t} className={rfTab===i?'is-active':''} aria-pressed={rfTab===i} onClick={()=>setRfTab(i)}><span>{t}</span></button>)}</div><div className="rf-advantages__stage"><div className="rf-advantages__media"><Img name={rfTab===0?'hydra-ai-detail.webp':'hydra-rf-source.webp'} alt={rfTab===0?'Fine engraved wood application concept':'Hydra RF laser source'}/></div><div className="rf-advantages__copy"><span className="eyebrow">{['FINER DETAIL','LONGER LIFESPAN','VERSATILE CONTROL'][rfTab]}</span><h3>{['A finer beam. A richer result.','Less maintenance. More uptime.','Tune the pulse to the process.'][rfTab]}</h3><p>{['A tight RF beam and responsive power control render subtle shades and intricate detail for premium personalization.','The sealed, air-cooled RF source is rated for 20,000–30,000 hours. No water chiller is required for the RF source; Hybrid DC tubes use water cooling.','Adjustable PWM supports fine engraving at high frequencies and stronger pulse energy at lower frequencies. Tune settings to your material and desired result.'][rfTab]}</p><strong>{['0.07 mm focused spot · Up to 2,000 DPI','20,000–30,000 hours · Air-cooled RF','Adjustable PWM · 38W / 70W RF'][rfTab]}</strong></div></div></div></section>

      <section className="power-guide" id="power-guide"><div className="power-guide__inner"><Heading eyebrow="TWO PURPOSE-BUILT CONFIGURATIONS" title="Choose the power that fits your work.">Pro and Hybrid share the Hydra production platform. Explore the source configuration designed for your workflow.</Heading><div className="power-switch" role="group" aria-label="Explore Hydra laser configurations">{['70W RF Pro','38W RF + DC Hybrid'].map((t,i)=><button key={t} className={powerTab===i?'is-active':''} aria-pressed={powerTab===i} onClick={()=>setPowerTab(i)}>{t}</button>)}</div><div className="power-proof-stage"><div className="power-proof-stage__media"><Img name={powerTab===0?'hydra-ai-detail.webp':'hydra-ai-acrylic.webp'} alt={powerTab===0?'Detailed RF wood engraving concept':'RF engraving and CO2 cutting application concept'}/></div><div className="power-proof-stage__copy"><span className="eyebrow">{powerTab===0?'HYDRA PRO GEN2':'HYDRA HYBRID GEN2'}</span><h3>{powerTab===0?'Dedicated RF performance.':'Detailed engraving. Powerful cutting.'}</h3><p>{powerTab===0?'70W RF for detailed grayscale, fine textures and professional batch engraving. Air-cooled operation with optional fiber expansion on supported configurations.':'38W RF engraving with a dedicated glass DC CO₂ cutting source. Multi-laser workflows through LightBurn and MakerBoost keep mixed jobs moving.'}</p><strong>{powerTab===0?'Hydra 7 · Hydra 9 · Hydra 13 · Hydra 16':'Hydra 9 / 100W · Hydra 13 / 130W · Hydra 16 / 150W'}</strong></div></div><p className="h-footnote">Fiber is optional and subject to compatibility and release availability. Standard 38W Hybrid requires upgrading to 70W RF before a fiber upgrade.</p></div></section>

<div className="capability-scroll__layout"><div className="capability-scroll__chapters">{chapters.map(c=><section className="capability-scroll__chapter" id={c.id} key={c.id}><header className="capability-scroll__chapter-heading"><h3>{c.title.replace('\n',' ')}</h3><p>{c.copy}</p></header><div className="capability-scroll__media-showcase"><article className="capability-scroll__feature capability-scroll__story"><button className="capability-scroll__media" onClick={()=>setPreview({name:c.image,alt:c.alt})} aria-label={`Enlarge ${c.label} image`}><Img name={c.image} alt={c.alt}/></button></article><div className="capability-scroll__support capability-scroll__support--icons">{c.proofs.map(([Icon,title,text])=><article key={title}><span className="capability-scroll__support-icon"><Icon size={28}/></span><div><h4>{title}</h4><p>{text}</p></div></article>)}</div></div>{c.metrics&&<div className="capability-scroll__proofs">{c.metrics.map(([v,l])=><article key={v}><Target size={24}/><strong>{v}</strong><span>{l}</span></article>)}</div>}</section>)}</div></div></section>

      <section className="h-section h-soft" id="workspaces"><div className="h-wrap"><Heading eyebrow="WORKSPACE AREA" title="The right size for your next step.">From focused personalization to large-format production, choose a bed that fits your ambition.</Heading><div className="h-workspaces">{Object.entries(models).map(([n,x])=><article key={n}><Img name={`hydra-${n}-hero.webp`} alt={`Hydra ${n} Gen2`}/><h3>Hydra {n}</h3><strong>{x.area}</strong><span>{x.inches}</span><p>{x.fit}</p><small>From {money(Math.min(...prices[n].variants.map(v=>v.price)))} USD</small><button className="h-link" onClick={()=>{chooseModel(n);navigate('top');}}>Explore Hydra {n}<ArrowUpRight size={16}/></button></article>)}</div></div></section>

      <section className="makerboost-proof" id="makerboost"><div className="makerboost-proof__inner"><div className="makerboost-proof__intro"><header className="makerboost-proof__header"><span className="eyebrow">MAKERBOOST SOFTWARE</span><h2>Out of the box, into creation.</h2></header><div className="makerboost-proof__copy"><p className="makerboost-proof__body">Built by OneLaser for Hydra. Automatic model detection, recommended parameters and registration-mark recognition simplify setup and repeat production.</p></div></div><div className="makerboost-proof__media"><Img name="hydra-makerboost.webp" alt="MakerBoost Hydra workflow and desktop interface"/></div></div></section>
      <section className="software-compatibility" id="software"><div className="software-compatibility__inner"><header className="software-compatibility__header"><span className="eyebrow">SOFTWARE</span><h2>Your software. Your way.</h2></header><article className="software-compatibility__stage"><div className="software-compatibility__copy"><p className="software-compatibility__body">Works with LightBurn, MakerBoost and RDWorks. The GT5 controller combines a 5-inch touchscreen with physical keys for file preview, diagnostics and offline production. Connect by USB, Ethernet or Wi-Fi.</p><p className="h-footnote">LightBurn license is optional and sold separately. Windows &amp; macOS supported.</p></div><div className="software-compatibility__media"><Img name="hydra-official-14.webp" alt="GT5 control system with touchscreen and keypad"/></div></article></div></section>

      <section className="product-opportunities" id="product-opportunities"><div className="product-opportunities__inner"><header className="product-opportunities__header"><span className="eyebrow">PRODUCT OPPORTUNITIES</span><h2>What could you sell with Hydra Gen2?</h2><p>Explore product categories designed for one-offs, repeat orders and batch production.</p></header><div className="product-opportunities__tabs" role="group" aria-label="Product opportunities">{opportunitySets.map((x,i)=><button key={x.label} className={opportunity===i?'is-active':''} aria-pressed={opportunity===i} onClick={()=>{setOpportunity(i);setProduct(0);}}><span>{String(i+1).padStart(2,'0')}</span><strong>{x.label}</strong></button>)}</div><div className="product-opportunities__panel"><header className="product-opportunities__category-copy"><p>{opportunitySets[opportunity].copy}</p></header><div className="product-card-grid" role="group" aria-label="Application products">{opportunitySets[opportunity].items.map(([name,image,material,process],i)=><button key={name} className={product===i?'product-card is-active':'product-card'} aria-pressed={product===i} onClick={()=>{setProduct(i);if(innerWidth<=760)document.getElementById('hydra-product-detail')?.scrollIntoView({behavior:reduced?'auto':'smooth',block:'nearest'});}}><span className="product-card__media"><Img name={image} alt={`${name} application concept`}/></span><span className="product-card__body"><small>{String(i+1).padStart(2,'0')}</small><strong>{name}</strong><span className="product-card__economics"><span>Material: <b>{material}</b></span><span>Process: <b>{process}</b></span></span></span></button>)}</div><div className="product-opportunities__selection"><article className="product-detail" id="hydra-product-detail"><div className="product-detail__facts"><span><small>Material</small><strong>{selectedProduct[2]}</strong></span><span><small>Process</small><strong>{selectedProduct[3]}</strong></span></div><p className="product-detail__setup"><small>Setup guidance</small><span>{selectedProduct[4]}</span></p></article><aside className="product-economics"><div className="product-economics__inner"><header className="product-economics__header"><span>PLAN YOUR APPLICATION</span><h4>Make the setup fit the work.</h4></header><p className="h-footnote">Choose the bed size, source and optional accessories with an engineer. Images are AI-generated application concepts.</p><Link secondary>Discuss your application</Link></div></aside></div></div></div></section>

      <section className="section materials" id="materials"><Heading eyebrow="MATERIALS THAT BECOME BUSINESSES" title="From material choice to sellable work.">Explore material-led projects that fit the Hydra production platform.</Heading><div className="material-gallery" role="region" aria-label="Hydra material slideshow" onMouseEnter={()=>setInteracting(true)} onMouseLeave={()=>setInteracting(false)} onFocusCapture={()=>setInteracting(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setInteracting(false);}} onTouchStart={e=>{setInteracting(true);matTouch.current=e.changedTouches[0].clientX;}} onTouchEnd={e=>{if(matTouch.current!==null&&Math.abs(e.changedTouches[0].clientX-matTouch.current)>44)selectMaterial(material+(e.changedTouches[0].clientX<matTouch.current?1:-1));matTouch.current=null;setInteracting(false);}}><div className="material-gallery__stage"><Img key={mat.image} name={mat.image} alt={`${mat.name} application inspiration`}/><div className="material-gallery__copy"><span>{mat.name}</span><h3>{mat.title}</h3><p>{mat.copy}</p><strong>{mat.mode}</strong></div></div><div className="material-tabs" role="group" aria-label="Materials">{materials.map((x,i)=><button className={material===i?'is-active':''} key={x.name} onClick={()=>selectMaterial(i)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const n=(i+(e.key==='ArrowRight'?1:3))%4;selectMaterial(n);e.currentTarget.parentElement.children[n].focus();}}} aria-pressed={material===i}><span className="material-tab__label"><x.icon size={23}/><span>{x.name}</span></span><small>{String(i+1).padStart(2,'0')}</small></button>)}</div><div className="material-progress" aria-hidden="true"><span key={`${material}-${epoch}`} className={paused||interacting||reduced?'is-paused':''} style={{'--material-progress-duration':'6000ms'}}/></div></div><div className="h-material-controls"><small>AI-generated application inspiration. Results depend on material and settings.</small><button className="thumb-arrow" aria-label={paused?'Play material slideshow':'Pause material slideshow'} aria-pressed={paused} onClick={()=>setPaused(v=>!v)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button className="thumb-arrow" aria-label="Previous material" onClick={()=>selectMaterial(material-1)}><CaretLeft size={18}/></button><button className="thumb-arrow" aria-label="Next material" onClick={()=>selectMaterial(material+1)}><CaretRight size={18}/></button></div></section>

      <section className="section specs" id="specifications"><div><Heading eyebrow="COMPLETE DETAILS" title="Specifications.">Compare workspaces and plan the setup that is right for your shop.</Heading><div className="h-spec-bar"><div className="h-tabs" role="group" aria-label="Specification model">{Object.keys(models).map(n=><button key={n} className={specModel===n?'is-active':''} aria-pressed={specModel===n} onClick={()=>setSpecModel(n)}>Hydra {n}</button>)}</div><a href={brochure} target="_blank" rel="noreferrer" className="h-link"><DownloadSimple size={18}/>Download brochure</a></div><div className="spec-list">{(()=>{const rows=[
        ['Work area',`${models[specModel].area} / ${models[specModel].inches}`],['Laser configurations',`70W RF Pro${specModel==='7'?'':` / 38W RF + ${models[specModel].dc}W DC Hybrid`}`],['Raster engraving speed','Up to 2,000 mm/s'],['Acceleration','4G'],['Maximum scanning precision','2,000 DPI'],['Repeat positioning accuracy','≤ 0.01 mm'],['Focused spot size','As small as 0.07 mm'],['Z-axis bed travel','225 mm / 8.86 in'],['Maximum bed load',models[specModel].load],['Machine dimensions (L × W × H)',models[specModel].dimensions],['Cooling','RF: air cooling. Hybrid DC source: water cooling.'],['Air assist','Built-in Smart Dual Air-Assist'],['Standard lens','2.5 in; optional 1.5 / 2 / 3 / 4 in lenses'],['Work tables','Honeycomb and blade table'],['Pass-through opening','Front-to-back, 20 mm height'],['Controller','GT5 · 5-inch touchscreen + keypad'],['Compatible software','LightBurn / MakerBoost / RDWorks'],['Connectivity','USB / Ethernet / Wi-Fi'],['Power supply','110V 60Hz / 220V 50Hz; confirm configuration and circuit requirements'],['Safety features','Lid and side-panel interlocks, lens-temperature monitoring, workbench temperature sensor, PM2.5 detector'],['Included essentials','Exhaust fan and ducting, air pump, tool kit, cables, lens removal tool and setup accessories']
      ]; return [{title:'Laser source & performance',rows:rows.slice(1,7)},{title:'Workspace & machine',rows:[rows[0],...rows.slice(7,10),rows[14]]},{title:'Control & software',rows:rows.slice(15,18)},{title:'Optics, cooling & safety',rows:[...rows.slice(10,14),rows[19]]},{title:'Electrical & included essentials',rows:[rows[18],rows[20]]}].map(g=><SpecGroup key={g.title} {...g}/>);})()}</div><p className="h-footnote">Confirm installed configuration, electrical circuit, ventilation, delivery access and any required cooling equipment with OneLaser before ordering.</p></div></section>

      <HydraComparison onPlay={setVideo}/>
      <HydraVideoRail onPlay={setVideo} owners/>
      <HydraDecisionPaths/>
      <section className="ownership-support" id="support"><div className="ownership-support__inner"><div className="ownership-support__grid">{[[Headset,'One Support. Real engineers.','Get direct support from the U.S.-based engineering team, plus 1-on-1 training and installation guidance.','https://www.1laser.com/pages/contact-us','Meet your support team'],[ShieldCheck,'Confidence beyond day one.','Review coverage, component terms and exclusions for your Hydra configuration before you buy.','https://www.1laser.com/pages/warranty-policy','View warranty terms'],[Truck,'Ready for arrival.','Plan delivery access, electrical supply, ventilation and cooling. Confirm current lead times and delivery arrangements with your engineer.',call,'Plan your installation']].map(([Icon,t,c,url,label],i)=><article className="ownership-support__card" key={t}><div className="ownership-support__card-top"><Icon size={26}/><span>{String(i+1).padStart(2,'0')}</span></div><div className="ownership-support__lead"><h3>{t}</h3></div><div className="ownership-support__details"><p>{c}</p><Link href={url} secondary>{label}</Link></div></article>)}</div></div></section>

      <section className="section faq" id="faq"><Heading eyebrow="BUYING QUESTIONS" title="Good answers before you commit."/><div className="faq-list">{[
        ['What is the difference between Pro and Hybrid?','Pro uses a dedicated 70W RF source for fine engraving and RF production. Hybrid pairs a 38W RF engraving source with a glass DC CO₂ cutting tube: 100W on Hydra 9, 130W on Hydra 13 and 150W on Hydra 16. Hydra 7 is offered as 70W RF Pro.'],
        ['Can I engrave bare metal?','Standard CO₂ sources are suited to compatible organic materials, glass and coated surfaces. Bare-metal processing requires an appropriate process or a compatible optional fiber upgrade. The standard 38W Hybrid does not support fiber without upgrading to 70W RF. Confirm upgrade availability with OneLaser.'],
        ['Does Hydra require a water chiller?','The RF source is air-cooled. The glass DC CO₂ source in Hybrid configurations is water-cooled and requires an appropriate cooling setup. Confirm the correct chiller and what is included with your quote.'],
        ['Which workspace should I choose?','Hydra 7 provides 700 × 500 mm; Hydra 9, 900 × 600 mm; Hydra 13, 1,300 × 900 mm; and Hydra 16, 1,600 × 1,000 mm. Choose around your largest regular job, batch layout, floor space and delivery access.'],
        ['What power outlet and ventilation do I need?','The specification lists 110V 60Hz / 220V 50Hz configurations. Required amperage and circuit sizing must be confirmed for the ordered machine and its accessories. Plan an appropriate exhaust route or compatible filtration system before installation.'],
        ['Can I engrave tumblers and bottles?','Yes, on laser-compatible materials using a compatible optional 4-pin rotary. Cylindrical work requires the rotary; confirm fit, object dimensions and clearance with OneLaser.'],
        ['What are the shipping and processing times?','Availability and delivery arrangements vary by model, configuration and destination. Ask OneLaser for the current processing estimate, shipping method and installation requirements for your order.'],
        ['Are accessories and software included in the displayed price?','Prices shown are for the selected machine configuration. Optional rotary, software licenses, filtration, lenses and fiber upgrades are separate. Review the official store or request an itemized quote for the complete setup.']
      ].map(([q,a],i)=><div className="faq-item" key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} aria-expanded={openFaq===i}><span>{q}</span><span>{openFaq===i?'−':'+'}</span></button>{openFaq===i&&<p>{a}</p>}</div>)}</div></section>
    </main><HomeFooter/>
    <button className={`back-to-top back-to-top--${topVisible?'visible':'hidden'}`} aria-label="Back to top" onClick={()=>navigate('top')}><CaretUp size={17}/><span>TOP</span></button>
    <div className={`sticky-buy hydra-sticky ${sticky?'is-visible':''}`} aria-hidden={!sticky} aria-label="Sticky purchase bar"><div><strong>Hydra {model} {config} Gen2</strong><span>{m.area}</span><small>U.S.-based lifetime support · 1-on-1 setup guidance</small></div><div className="sticky-buy__price"><div className="sticky-buy__amounts"><span><strong>{money(variant.price)}</strong></span></div></div><a className="primary-cta" href={purchaseUrl} tabIndex={sticky?0:-1} target="_blank" rel="noreferrer" onClick={()=>trackEvent('purchase_intent',{model,configuration:config,placement:'sticky'})}>Configure<ArrowUpRight size={17}/></a></div>
    {video&&<HydraVideoModal item={video} onClose={closeVideo}/>}
    {preview&&<Preview item={preview} close={closePreview}/>}
  </div>;
}
